version: '3.9'

services:
  notification-engine:
    ports:
      - "6001:8000"
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    build:
      context: ./docker
      dockerfile: Dockerfile.local
    restart: always
